### ISSUE TITLE
Category Theory for Programmers

### ISSUE THREAD

**Issue by delta4d** [delta4d/RTFB#2]
https://github.com/hmemcpy/milewski-ctfp-pdf

### Part One
- [ ] Category: The Essence of Composition
- [ ] Types and Functions
- [ ] Categories Great and Small
- [ ] Kleisli Categories
- [ ] Products and Coproducts
- [ ] Simple Algebraic Data Types
- [ ] Functors
- [ ] Functoriality
- [ ] Function Types
- [ ] Natural Transformations
### Part Two
- [ ] Declarative Programming
- [ ] Limits and Colimits
- [ ] Free Monoids
- [ ] Representable Functors
- [ ] The Yoneda Lemma
- [ ] Yoneda Embedding
### Part Three
- [ ] It's All About Morphisms
- [ ] Adjunctions
- [ ] Free/Forgetful Adjunctions
- [ ] Monads: Programmer's Definition
- [ ] Monads and Effects
- [ ] Monads Categorically
- [ ] Comonads
- [ ] F-Algebras
- [ ] Algebras for Monads
- [ ] Ends and Coends
- [ ] Kan Extensions
- [ ] Enriched Categories
- [ ] Topoi
- [ ] Lawvere Theories
- [ ] Monads, Monoids, and Categories
